Repository dnd-side-project/dnd-5th-3-android, pull requests merged in 2021-08, with the labels that each got.

#10 #3 [layout] 메인 및 이메일 계정 로그인 화면 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/how/about/it/view/EmailLoginFragment.kt
  app/src/main/java/how/about/it/view/LoginActivity.kt
  app/src/main/java/how/about/it/view/ToolbarActivity.kt
  app/src/main/java/how/about/it/view/login/EmailLoginFragment.kt
  app/src/main/java/how/about/it/view/login/EmailPasswordResetFragment.kt
  app/src/main/java/how/about/it/view/login/LoginActivity.kt
  app/src/main/res/drawable/activity_login_background.xml
  app/src/main/res/drawable/button_login_email.xml
  app/src/main/res/drawable/button_login_email_off.xml
  app/src/main/res/drawable/button_login_google.xml
  app/src/main/res/drawable/button_login_google_img.xml
  app/src/main/res/drawable/ic_delete_edittext.xml
  app/src/main/res/drawable/ic_logo_google.xml
  app/src/main/res/drawable/ic_logo_moomool.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_toolbar.xml
  app/src/main/res/layout/fragment_email_login.xml
  app/src/main/res/layout/fragment_email_password_reset.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: layout

#16 #15 [layout] NotificationFragment
  app/src/main/java/how/about/it/view/feed/FeedFragment.kt
  app/src/main/java/how/about/it/view/notification/NotificationFragment.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_notification_empty.xml
  app/src/main/res/drawable/ic_notification_not_read.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: layout

#19 #6 [layout] Modify Default Button Name
  app/src/main/java/how/about/it/view/login/EmailLoginFragment.kt
  app/src/main/java/how/about/it/view/login/EmailPasswordResetFragment.kt
  app/src/main/java/how/about/it/view/signup/EmailSignupSetIDFragment.kt
  app/src/main/java/how/about/it/view/signup/EmailSignupSetNicknameFragment.kt
  app/src/main/java/how/about/it/view/signup/EmailSignupSetPasswordFragment.kt
  app/src/main/res/drawable/button_default_disable.xml
  app/src/main/res/drawable/button_default_enable.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_email_login.xml
  app/src/main/res/layout/fragment_email_password_reset.xml
  app/src/main/res/layout/fragment_email_signup_set_id.xml
  app/src/main/res/layout/fragment_email_signup_set_nickname.xml
  app/src/main/res/layout/fragment_email_signup_set_password.xml
Labels: layout

#21 #20 [layout] ProfileFragment
  app/src/main/java/how/about/it/view/profile/ProfileFragment.kt
  app/src/main/res/drawable/button_duplicate_check.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: layout

#23 #22 [layout] DetailPostFragment
  app/build.gradle
  app/src/main/java/how/about/it/view/detailPost/DetailPostFragment.kt
  app/src/main/res/drawable/background_reaction_fab_round_16.xml
  app/src/main/res/drawable/background_small_emoji_round_20.xml
  app/src/main/res/drawable/background_small_emoji_voted_round_20.xml
  app/src/main/res/drawable/ic_alarm.xml
  app/src/main/res/drawable/ic_comments_agree.xml
  app/src/main/res/drawable/ic_comments_disagree.xml
  app/src/main/res/drawable/ic_comments_none.xml
  app/src/main/res/drawable/ic_emoji_agree.xml
  app/src/main/res/drawable/ic_emoji_disagree.xml
  app/src/main/res/drawable/ic_emoji_small_funny.xml
  app/src/main/res/drawable/ic_emoji_small_oh.xml
  app/src/main/res/drawable/ic_emoji_small_sad.xml
  app/src/main/res/drawable/ic_emoji_small_umm.xml
  app/src/main/res/drawable/ic_emoji_small_wow.xml
  app/src/main/res/drawable/ic_emoji_vote_complete_agree.xml
  app/src/main/res/drawable/ic_emoji_vote_complete_disagree.xml
  app/src/main/res/drawable/ic_judge.xml
  app/src/main/res/drawable/ic_more_horizontal.xml
  app/src/main/res/drawable/ic_x_sign.xml
  app/src/main/res/layout/fragment_detail_post.xml
  app/src/main/res/layout/item_comments.xml
  app/src/main/res/layout/item_detail_post_vote.xml
  app/src/main/res/values/strings.xml
Labels: layout

#25 #24 [feature] PopupMenu in FeedFragment
  app/src/main/java/how/about/it/view/feed/FeedFragment.kt
  app/src/main/java/how/about/it/view/feed/viewmodel/FeedViewModel.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/menu/menu_feed_toggle.xml
  app/src/main/res/values/themes.xml
Labels: feature

#27 #26 [feature] MyPage Category Selector
  app/src/main/java/how/about/it/view/feed/FeedFragment.kt
  app/src/main/java/how/about/it/view/mypage/MyPageFragment.kt
  app/src/main/java/how/about/it/view/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: feature

#29 #28 [layout] DetailPostFragment 보완
  app/src/main/AndroidManifest.xml
  app/src/main/java/how/about/it/view/detailPost/DetailPostFragment.kt
  app/src/main/res/drawable/background_dim.xml
  app/src/main/res/drawable/ic_emoji_small_umm.xml
  app/src/main/res/layout/fragment_detail_post.xml
  app/src/main/res/layout/item_comments.xml
  app/src/main/res/layout/item_detail_post_vote.xml
Labels: bug, layout

#31 #30 [layout] WriteFragment
  app/src/main/java/how/about/it/view/main/MainActivity.kt
  app/src/main/java/how/about/it/view/write/TempListWriteFragment.kt
  app/src/main/java/how/about/it/view/write/TempSavedWriteFragment.kt
  app/src/main/java/how/about/it/view/write/WriteFragment.kt
  app/src/main/res/drawable/ic_check_sign.xml
  app/src/main/res/drawable/ic_trashbin.xml
  app/src/main/res/layout/fragment_temp_list_write.xml
  app/src/main/res/layout/fragment_temp_saved_write.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/item_write_save_temp.xml
  app/src/main/res/menu/menu_write_temp_recall_toolbar.xml
  app/src/main/res/menu/menu_write_temp_toolbar.xml
  app/src/main/res/menu/menu_write_toolbar.xml
Labels: layout

#34 #32 [layout] WriteFragment 보완
  app/src/main/java/how/about/it/view/ToastDefaultBlack.kt
  app/src/main/java/how/about/it/view/detailPost/DetailPostFragment.kt
  app/src/main/java/how/about/it/view/write/TempListWriteFragment.kt
  app/src/main/java/how/about/it/view/write/TempSavedWriteFragment.kt
  app/src/main/java/how/about/it/view/write/WriteFragment.kt
  app/src/main/res/drawable/ic_archive.xml
  app/src/main/res/drawable/ic_picture.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/toast_default_black.xml
  app/src/main/res/menu/menu_write_temp_toolbar.xml
  app/src/main/res/menu/menu_write_toolbar.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: bug, layout

#37 #36 [feature] Comment FloatingActionButton Animation
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/java/how/about/it/view/comment/viewmodel/CommentViewModel.kt
  app/src/main/res/drawable/background_reaction_fab_round_16.xml
  app/src/main/res/drawable/ic_comment_blue.xml
  app/src/main/res/drawable/ic_comment_brown.xml
  app/src/main/res/drawable/ic_comment_green.xml
  app/src/main/res/drawable/ic_comment_red.xml
  app/src/main/res/drawable/ic_comment_yellow.xml
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/values/strings.xml
Labels: feature

#39 #38 [layout] Dialog
  app/src/main/java/how/about/it/view/DialogDefaultConfirm.kt
  app/src/main/java/how/about/it/view/detailPost/DetailPostFragment.kt
  app/src/main/java/how/about/it/view/login/EmailPasswordResetFragment.kt
  app/src/main/java/how/about/it/view/profile/ProfileFragment.kt
  app/src/main/java/how/about/it/view/write/TempListWriteFragment.kt
  app/src/main/java/how/about/it/view/write/TempSavedWriteFragment.kt
  app/src/main/java/how/about/it/view/write/WriteFragment.kt
  app/src/main/res/layout/activity_toolbar.xml
  app/src/main/res/layout/dialog_default_confirm.xml
  app/src/main/res/layout/fragment_email_login.xml
  app/src/main/res/layout/fragment_email_password_reset.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/item_write_save_temp.xml
  app/src/main/res/layout/toast_default_black.xml
  app/src/main/res/menu/menu_detail_post_mine_toolbar.xml
  app/src/main/res/menu/menu_write_temp_recall_toolbar.xml
  app/src/main/res/menu/menu_write_temp_toolbar.xml
  app/src/main/res/menu/menu_write_toolbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: layout

#41 #40 [layout] FragmentComment
  app/src/main/res/drawable/background_flexbox_divider.xml
  app/src/main/res/drawable/ic_comment_reaction_empty.xml
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/layout/item_re_comment.xml
  app/src/main/res/values/strings.xml
Labels: layout

#43 #42 [feature] Comment Click Event
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/menu/menu_comment.xml
  app/src/main/res/values/strings.xml
Labels: feature

#45 #44 [feature] TimeChangerUtil
  app/src/main/java/how/about/it/util/TimeChangerUtil.kt
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/layout/item_comments.xml
  app/src/main/res/layout/item_re_comment.xml
  app/src/main/res/values/strings.xml
Labels: feature

#47 #46 [layout] OnBoarding
  app/src/main/java/how/about/it/view/onboarding/OnBoardingFirstFragment.kt
  app/src/main/java/how/about/it/view/onboarding/OnBoardingFourthFragment.kt
  app/src/main/java/how/about/it/view/onboarding/OnBoardingFragment.kt
  app/src/main/java/how/about/it/view/onboarding/OnBoardingSecondFragment.kt
  app/src/main/java/how/about/it/view/onboarding/OnBoardingThirdFragment.kt
  app/src/main/res/drawable/ic_on_boarding_first.9.png
  app/src/main/res/drawable/ic_on_boarding_fourth.9.png
  app/src/main/res/drawable/ic_on_boarding_second.9.png
  app/src/main/res/drawable/ic_on_boarding_selected.xml
  app/src/main/res/drawable/ic_on_boarding_third.9.png
  app/src/main/res/drawable/ic_on_boarding_unselected.xml
  app/src/main/res/drawable/selector_on_boarding_indicator.xml
  app/src/main/res/layout/fragment_on_boarding.xml
  app/src/main/res/layout/fragment_on_boarding_first.xml
  app/src/main/res/layout/fragment_on_boarding_fourth.xml
  app/src/main/res/layout/fragment_on_boarding_second.xml
  app/src/main/res/layout/fragment_on_boarding_third.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: layout

#49 #48 [feature] Lottie in Comment
  app/build.gradle
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/raw/lottie_reaction_blue.json
  app/src/main/res/raw/lottie_reaction_brown.json
  app/src/main/res/raw/lottie_reaction_green.json
  app/src/main/res/raw/lottie_reaction_red.json
  app/src/main/res/raw/lottie_reaction_yellow.json
Labels: feature

#51 #50 [layout] Update CommentFragment
  app/src/main/java/how/about/it/util/FloatingAnimationUtil.kt
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/layout/item_comment.xml
Labels: layout

#53 #52 [layout] VoteFragment
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/java/how/about/it/view/detailPost/DetailPostFragment.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/java/how/about/it/view/vote/viewmodel/VoteViewModel.kt
  app/src/main/res/drawable/ic_vote_agree.xml
  app/src/main/res/drawable/ic_vote_complete_agree.xml
  app/src/main/res/drawable/ic_vote_complete_disagree.xml
  app/src/main/res/drawable/ic_vote_disagree.xml
  app/src/main/res/layout/fragment_detail_post.xml
  app/src/main/res/layout/fragment_vote.xml
Labels: layout

#55 #54 [feature] 임시 저장 기능 구현
  app/build.gradle
  app/src/main/java/how/about/it/database/Post.kt
  app/src/main/java/how/about/it/database/SharedManager.kt
  app/src/main/java/how/about/it/database/TempPostDao.kt
  app/src/main/java/how/about/it/database/TempPostDatabase.kt
  app/src/main/java/how/about/it/database/User.kt
  app/src/main/java/how/about/it/model/RequestLogin.kt
  app/src/main/java/how/about/it/repository/TempPostRepository.kt
  app/src/main/java/how/about/it/view/login/EmailLoginFragment.kt
  app/src/main/java/how/about/it/view/write/TempListWriteAdapter.kt
  app/src/main/java/how/about/it/view/write/TempListWriteFragment.kt
  app/src/main/java/how/about/it/view/write/TempSavedWriteFragment.kt
  app/src/main/java/how/about/it/view/write/WriteFragment.kt
  app/src/main/java/how/about/it/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/fragment_temp_list_write.xml
  app/src/main/res/layout/fragment_temp_saved_write.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/item_write_save_temp.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#57 #56 [bug] Data Bug Fix
  app/build.gradle
  app/src/main/java/how/about/it/database/Post.kt
  app/src/main/java/how/about/it/database/SharedManager.kt
  app/src/main/java/how/about/it/database/User.kt
  app/src/main/java/how/about/it/model/RequestLogin.kt
  app/src/main/java/how/about/it/view/login/EmailLoginFragment.kt
Labels: bug

#59 #58 [feature] CountDownTimer in Vote
  app/src/main/java/how/about/it/util/TimeChangerUtil.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
Labels: feature

#62 #60 [feature] ViewPagerChangeCallBack in OnBoarding
  app/src/main/java/how/about/it/view/onboarding/OnBoardingFragment.kt
  app/src/main/res/layout/fragment_on_boarding.xml
  app/src/main/res/values/strings.xml
Labels: feature

#64 #63 [feature] Image Upload
  app/src/main/AndroidManifest.xml
  app/src/main/java/how/about/it/database/Post.kt
  app/src/main/java/how/about/it/view/write/TempListWriteAdapter.kt
  app/src/main/java/how/about/it/view/write/TempSavedWriteFragment.kt
  app/src/main/java/how/about/it/view/write/WriteFragment.kt
Labels: layout

#66 #65 [bug] Modify Data class variable name
  app/src/main/java/how/about/it/database/Post.kt
  app/src/main/java/how/about/it/database/SharedManager.kt
  app/src/main/java/how/about/it/database/User.kt
  app/src/main/java/how/about/it/model/RequestLogin.kt
  app/src/main/java/how/about/it/network/RequestToServer.kt
  app/src/main/java/how/about/it/view/login/EmailLoginFragment.kt
  app/src/main/java/how/about/it/view/write/TempListWriteAdapter.kt
  app/src/main/java/how/about/it/view/write/TempSavedWriteFragment.kt
  app/src/main/java/how/about/it/view/write/WriteFragment.kt
Labels: bug

#68 #67 [bug] TimeChangerUtil when calTime < 60
  app/src/main/java/how/about/it/util/TimeChangerUtil.kt
Labels: bug

#70 #69 [bug] Modify WriteFragment Time Format
  app/src/main/java/how/about/it/view/write/WriteFragment.kt
Labels: bug

#73 #72 [feature] Create Reaction(emoji) and Delete Reaction(emoji)
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/java/how/about/it/view/comment/ResponseComment.kt
  app/src/main/java/how/about/it/view/comment/viewmodel/CommentViewModel.kt
  app/src/main/res/layout/item_comment.xml
Labels: feature

#74 #3 [feature] 이메일 회원가입 기능 구현
  app/src/main/java/how/about/it/model/RequestMember.kt
  app/src/main/java/how/about/it/repository/SignupRepository.kt
  app/src/main/java/how/about/it/view/signup/EmailSignupSetIDFragment.kt
  app/src/main/java/how/about/it/view/signup/EmailSignupSetNicknameFragment.kt
  app/src/main/java/how/about/it/view/signup/EmailSignupSetPasswordFragment.kt
  app/src/main/java/how/about/it/viewmodel/SignupViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_email_signup_set_id.xml
  app/src/main/res/layout/fragment_email_signup_set_nickname.xml
  app/src/main/res/layout/fragment_email_signup_set_password.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: feature

#76 #75 [feature] FeedList Network
  app/src/main/java/how/about/it/network/RequestToServer.kt
  app/src/main/java/how/about/it/network/feed/FeedInterface.kt
  app/src/main/java/how/about/it/network/feed/FeedService.kt
  app/src/main/java/how/about/it/network/feed/FeedServiceImpl.kt
  app/src/main/java/how/about/it/view/feed/FeedFragment.kt
  app/src/main/java/how/about/it/view/feed/ResponseMainFeed.kt
  app/src/main/java/how/about/it/view/feed/repository/FeedRepository.kt
  app/src/main/java/how/about/it/view/feed/viewmodel/FeedViewModel.kt
  app/src/main/java/how/about/it/view/feed/viewmodel/FeedViewModelFactory.kt
  app/src/main/res/values/strings.xml
Labels: feature

#78 #77 [feature] E-Mail Login enhancements
  app/src/main/java/how/about/it/database/SharedManager.kt
  app/src/main/java/how/about/it/model/RequestLogin.kt
  app/src/main/java/how/about/it/network/RequestInterface.kt
  app/src/main/java/how/about/it/network/RequestToServer.kt
  app/src/main/java/how/about/it/repository/LoginRepository.kt
  app/src/main/java/how/about/it/view/login/EmailLoginFragment.kt
  app/src/main/java/how/about/it/view/login/LoginActivity.kt
  app/src/main/java/how/about/it/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_email_login.xml
  app/src/main/res/values/strings.xml
Labels: feature

#81 #79 [feature] Setting FeedAdapter
  app/src/main/java/how/about/it/view/feed/FeedFragment.kt
  app/src/main/java/how/about/it/view/feed/adapter/FeedBottomAdapter.kt
  app/src/main/java/how/about/it/view/feed/adapter/FeedTopAdapter.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_feed_bottom.xml
  app/src/main/res/layout/item_feed_top.xml
Labels: feature

#82 #80 [layout] DataBinding for Feed
  app/src/main/java/how/about/it/util/BindingAdapter.kt
  app/src/main/java/how/about/it/util/TimeChangerUtil.kt
  app/src/main/java/how/about/it/view/feed/ResponseMainFeed.kt
  app/src/main/java/how/about/it/view/feed/adapter/FeedBottomAdapter.kt
  app/src/main/java/how/about/it/view/feed/adapter/FeedTopAdapter.kt
  app/src/main/res/drawable/background_progress_permit_round_10.xml
  app/src/main/res/drawable/background_progress_reject_round_10.xml
  app/src/main/res/drawable/ic_feed_image_empty.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed_bottom.xml
  app/src/main/res/layout/item_feed_top.xml
  app/src/main/res/values/strings.xml
Labels: layout

#85 #84 [feature] Authorization Header, Upload Post
  app/src/main/java/how/about/it/model/RequestPost.kt
  app/src/main/java/how/about/it/network/RequestInterface.kt
  app/src/main/java/how/about/it/network/RequestToServer.kt
  app/src/main/java/how/about/it/repository/WriteRepository.kt
  app/src/main/java/how/about/it/view/write/TempListWriteFragment.kt
  app/src/main/java/how/about/it/view/write/TempSavedWriteFragment.kt
  app/src/main/java/how/about/it/view/write/WriteFragment.kt
  app/src/main/java/how/about/it/viewmodel/WriteViewModel.kt
Labels: feature

#86 #83 [feature] FeedClickListener
  app/build.gradle
  app/src/main/java/how/about/it/view/feed/adapter/FeedBottomAdapter.kt
  app/src/main/java/how/about/it/view/feed/adapter/FeedTopAdapter.kt
  app/src/main/res/navigation/nav_graph.xml
  build.gradle
Labels: feature

#90 #89 [feature] RequestVote
  app/src/main/java/how/about/it/view/vote/RequestVote.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/java/how/about/it/view/vote/viewmodel/VoteViewModel.kt
Labels: feature

#92 #91 [feature] Update CoroutineScope for collect
  app/build.gradle
  app/src/main/java/how/about/it/view/feed/FeedFragment.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
Labels: feature

#94 #93 [layout] DataBinding for Comment in Vote
  app/src/main/java/how/about/it/util/BindingAdapter.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/java/how/about/it/view/vote/adapter/VoteCommentAdapter.kt
  app/src/main/res/drawable/ic_comments_disagree.xml
  app/src/main/res/drawable/ic_comments_none.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/values/strings.xml
Labels: layout

#96 #95 [feature] ReComment Network
  app/src/main/java/how/about/it/network/RequestToServer.kt
  app/src/main/java/how/about/it/network/comment/CommentInterface.kt
  app/src/main/java/how/about/it/network/comment/CommentService.kt
  app/src/main/java/how/about/it/network/comment/CommentServiceImpl.kt
  app/src/main/java/how/about/it/util/BindingAdapter.kt
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/java/how/about/it/view/comment/adapter/ReCommentAdapter.kt
  app/src/main/java/how/about/it/view/comment/repository/CommentRepository.kt
  app/src/main/java/how/about/it/view/comment/viewmodel/CommentViewModel.kt
  app/src/main/java/how/about/it/view/comment/viewmodel/CommentViewModelFactory.kt
  app/src/main/res/layout/item_re_comment.xml
Labels: feature

#98 #97 [layout] Change User Password Fragmen
  app/src/main/java/how/about/it/view/profile/ChangePasswordFragment.kt
  app/src/main/java/how/about/it/view/profile/ProfileFragment.kt
  app/src/main/res/layout/fragment_change_password.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: layout

#100 #99 [feature] User Logout, Layout Setting Fragment
  app/src/main/java/how/about/it/view/feed/FeedFragment.kt
  app/src/main/java/how/about/it/view/mypage/MyPageFragment.kt
  app/src/main/java/how/about/it/view/setting/SettingFragment.kt
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature, layout

#102 [feature] Update PermitCount and RejectCount #101
  app/src/main/java/how/about/it/util/BindingAdapter.kt
  app/src/main/java/how/about/it/view/vote/ResponseFeedDetail.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/java/how/about/it/view/vote/viewmodel/VoteViewModel.kt
  app/src/main/res/layout/fragment_vote.xml
Labels: feature

#104 #103 [layout] Comment Edittext fragment_comment
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/values/strings.xml
Labels: layout

#106 #105 [feature] Add voteDeadLine in Feed
  app/src/main/java/how/about/it/view/feed/ResponseMainFeed.kt
  app/src/main/java/how/about/it/view/feed/adapter/FeedBottomAdapter.kt
  app/src/main/java/how/about/it/view/feed/adapter/FeedTopAdapter.kt
Labels: feature

#108 #107 [bug] Update String Resources for Feed Request
  app/src/main/res/values/strings.xml
Labels: bug

#110 #109 [layout] Vote More Button
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/menu/menu_feed_delete.xml
Labels: layout

#113 #112 [layout] Update Main BottomNavigation Color
  app/src/main/res/layout/activity_main.xml
Labels: layout

#115 #114 [feature] Image Upload Server
  app/src/main/java/how/about/it/model/RequestPost.kt
  app/src/main/java/how/about/it/network/RequestInterface.kt
  app/src/main/java/how/about/it/repository/WriteRepository.kt
  app/src/main/java/how/about/it/view/write/WriteFragment.kt
  app/src/main/java/how/about/it/viewmodel/WriteViewModel.kt
Labels: feature

#117 #116 [feature] Feed Data
  app/src/main/java/how/about/it/util/BindingAdapter.kt
  app/src/main/java/how/about/it/view/feed/adapter/FeedBottomAdapter.kt
  app/src/main/java/how/about/it/view/feed/adapter/FeedTopAdapter.kt
  app/src/main/java/how/about/it/view/feed/viewmodel/FeedViewModel.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/res/drawable/background_progress_empty_thumb.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/layout/item_feed_bottom.xml
  app/src/main/res/layout/item_feed_top.xml
  app/src/main/res/values/strings.xml
Labels: feature

#119 #118 [feature] PagerSnapHelper for RvFeedTop
  app/src/main/java/how/about/it/view/feed/FeedFragment.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/values/strings.xml
Labels: feature

#121 #120 [feature] Skip OnBoardingFragment
  app/src/main/java/how/about/it/database/SharedManager.kt
  app/src/main/java/how/about/it/repository/LoginRepository.kt
  app/src/main/java/how/about/it/view/onboarding/OnBoardingFragment.kt
  app/src/main/res/values/strings.xml
Labels: feature

#124 #111 [feature] Feed Delete
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/java/how/about/it/view/vote/viewmodel/VoteViewModel.kt
Labels: feature

#127 #125 [feature] Request Comment Post
  app/src/main/java/how/about/it/network/vote/VoteInterface.kt
  app/src/main/java/how/about/it/network/vote/VoteService.kt
  app/src/main/java/how/about/it/network/vote/VoteServiceImpl.kt
  app/src/main/java/how/about/it/view/vote/RequestPostComment.kt
  app/src/main/java/how/about/it/view/vote/ResponsePostComment.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/java/how/about/it/view/vote/repository/VoteRepository.kt
  app/src/main/java/how/about/it/view/vote/viewmodel/VoteViewModel.kt
  app/src/main/res/layout/fragment_vote.xml
Labels: feature

#128 #126 [feature] E-Mail, Nickname Duplicate Check
  app/src/main/java/how/about/it/network/RequestInterface.kt
  app/src/main/java/how/about/it/network/RequestToServer.kt
  app/src/main/java/how/about/it/repository/SignupRepository.kt
  app/src/main/java/how/about/it/view/signup/EmailSignupSetIDFragment.kt
  app/src/main/java/how/about/it/view/signup/EmailSignupSetNicknameFragment.kt
  app/src/main/java/how/about/it/viewmodel/SignupViewModel.kt
Labels: feature

#131 #129 [feature] Comment Click Event
  app/src/main/java/how/about/it/view/vote/adapter/VoteCommentAdapter.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#135 #132 [feature] Delete Comment
  app/src/main/java/how/about/it/network/vote/VoteInterface.kt
  app/src/main/java/how/about/it/network/vote/VoteService.kt
  app/src/main/java/how/about/it/network/vote/VoteServiceImpl.kt
  app/src/main/java/how/about/it/util/BindingAdapter.kt
  app/src/main/java/how/about/it/view/comment/ResponseComment.kt
  app/src/main/java/how/about/it/view/vote/RequestCommentId.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/java/how/about/it/view/vote/adapter/VoteCommentAdapter.kt
  app/src/main/java/how/about/it/view/vote/repository/VoteRepository.kt
  app/src/main/java/how/about/it/view/vote/viewmodel/VoteViewModel.kt
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_re_comment.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#136 #133 [layout] CommentUpdateFragment
  app/src/main/java/how/about/it/view/commentupdate/CommentUpdateFragment.kt
  app/src/main/java/how/about/it/view/vote/adapter/VoteCommentAdapter.kt
  app/src/main/res/layout/fragment_comment_update.xml
Labels: layout

#137 #134 [feature] Update Comment
  app/src/main/java/how/about/it/network/comment/CommentInterface.kt
  app/src/main/java/how/about/it/network/comment/CommentService.kt
  app/src/main/java/how/about/it/network/comment/CommentServiceImpl.kt
  app/src/main/java/how/about/it/view/comment/repository/CommentRepository.kt
  app/src/main/java/how/about/it/view/comment/viewmodel/CommentViewModel.kt
  app/src/main/java/how/about/it/view/commentupdate/CommentUpdateFragment.kt
  app/src/main/java/how/about/it/view/commentupdate/RequestPutComment.kt
  app/src/main/res/layout/fragment_comment_update.xml
  app/src/main/res/values/strings.xml
Labels: feature

#139 #138 [bug] Comment Update TextColor
  app/src/main/java/how/about/it/view/commentupdate/CommentUpdateFragment.kt
  app/src/main/res/layout/fragment_comment_update.xml
Labels: bug

#140 #130 [feature] Request ReComment Post
  app/src/main/java/how/about/it/network/comment/CommentInterface.kt
  app/src/main/java/how/about/it/network/comment/CommentService.kt
  app/src/main/java/how/about/it/network/comment/CommentServiceImpl.kt
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/java/how/about/it/view/comment/RequestPostReComment.kt
  app/src/main/java/how/about/it/view/comment/repository/CommentRepository.kt
  app/src/main/java/how/about/it/view/comment/viewmodel/CommentViewModel.kt
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/layout/item_re_comment.xml
Labels: feature

#144 #143 [layout] Write, Temp Post Fragment
  app/src/main/res/layout/fragment_temp_list_write.xml
  app/src/main/res/layout/fragment_temp_saved_write.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/item_write_save_temp.xml
Labels: layout

#145 #142 [feature] Comment Update Delete in CommentFragment
  app/src/main/java/how/about/it/network/comment/CommentInterface.kt
  app/src/main/java/how/about/it/network/comment/CommentService.kt
  app/src/main/java/how/about/it/network/comment/CommentServiceImpl.kt
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/java/how/about/it/view/comment/adapter/ReCommentAdapter.kt
  app/src/main/java/how/about/it/view/comment/repository/CommentRepository.kt
  app/src/main/java/how/about/it/view/comment/viewmodel/CommentViewModel.kt
  app/src/main/res/layout/item_re_comment.xml
Labels: feature

#147 #146 [bug] Upload Post DobuleQuote Insert Bug Fix
  app/build.gradle
  app/src/main/java/how/about/it/network/RequestToServer.kt
Labels: bug

#149 #148 [bug] Upload Post NoImage Bug Fix
  app/src/main/java/how/about/it/repository/WriteRepository.kt
Labels: bug

#156 #141 [feature] Emoji Network
  app/src/main/java/how/about/it/network/comment/CommentInterface.kt
  app/src/main/java/how/about/it/network/comment/CommentService.kt
  app/src/main/java/how/about/it/network/comment/CommentServiceImpl.kt
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/java/how/about/it/view/comment/RequestPostEmoji.kt
  app/src/main/java/how/about/it/view/comment/RequestPutEmoji.kt
  app/src/main/java/how/about/it/view/comment/ResponsePostEmoji.kt
  app/src/main/java/how/about/it/view/comment/repository/CommentRepository.kt
  app/src/main/java/how/about/it/view/comment/viewmodel/CommentViewModel.kt
  app/src/main/res/layout/item_comment.xml
Labels: feature

#158 #157 [layout] setImageClipToOutLine
  app/src/main/java/how/about/it/view/feed/adapter/FeedBottomAdapter.kt
  app/src/main/java/how/about/it/view/feed/adapter/FeedTopAdapter.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/layout/item_feed_bottom.xml
  app/src/main/res/layout/item_feed_top.xml
Labels: layout

#160 #159 [layout] ThumbOffset
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/layout/item_feed_top.xml
Labels: layout

#164 #163 [feature] Feed SwipeRefreshLayout
  app/src/main/java/how/about/it/view/feed/FeedFragment.kt
  app/src/main/res/layout/fragment_feed.xml
Labels: feature

#167 #166 [layout] Update themes.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: layout

#168 #165 [layout] Delete Unused Resources and Update strings.xml
  app/src/main/java/how/about/it/view/detailPost/DetailPostFragment.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/res/drawable/background_dim.xml
  app/src/main/res/drawable/ic_emoji_agree.xml
  app/src/main/res/drawable/ic_emoji_disagree.xml
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/layout/fragment_detail_post.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/layout/item_comments.xml
  app/src/main/res/layout/item_detail_post_vote.xml
  app/src/main/res/menu/menu_detail_post_mine_toolbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: layout

#170 #169 [bug] Change Nickname Dialog Bug Fix
  app/src/main/java/how/about/it/view/profile/ProfileFragment.kt
  app/src/main/java/how/about/it/viewmodel/ProfileViewModel.kt
Labels: bug

#172 #171 [layout] Apply Lottie Image for RequestVote
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/raw/lottie_agree.json
  app/src/main/res/raw/lottie_disagree.json
Labels: feature, layout

#176 #175 [bug] VoteFragment Image
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/res/layout/fragment_vote.xml
Labels: bug

#180 #179 [refactoring] FeedFragment Refactoring
  app/src/main/java/how/about/it/view/feed/FeedFragment.kt
  app/src/main/java/how/about/it/view/feed/adapter/FeedBottomAdapter.kt
  app/src/main/java/how/about/it/view/feed/adapter/FeedTopAdapter.kt
  app/src/main/java/how/about/it/view/feed/viewmodel/FeedViewModel.kt
  app/src/main/res/layout/item_feed_top.xml
Labels: refactoring

#178 #177 [layout] Create Notice Fragment in SettingFragment
  app/src/main/java/how/about/it/view/notice/NoticeListFragment.kt
  app/src/main/java/how/about/it/view/notice/NoticePostFragment.kt
  app/src/main/java/how/about/it/view/setting/SettingFragment.kt
  app/src/main/res/layout/fragment_notice_list.xml
  app/src/main/res/layout/fragment_notice_post.xml
  app/src/main/res/layout/item_notice.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: layout

#182 #181 [layout] Update FeedFragment Layout
  app/src/main/java/how/about/it/view/feed/FeedFragment.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed_top.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: layout

#186 #184 [refactoring] CommentFragment
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/java/how/about/it/view/comment/ResponseComment.kt
  app/src/main/java/how/about/it/view/comment/viewmodel/CommentViewModel.kt
Labels: refactoring

#185 #183 [feature] Update Nickname
  app/src/main/java/how/about/it/database/SharedManager.kt
  app/src/main/java/how/about/it/model/RequestProfileUpdate.kt
  app/src/main/java/how/about/it/network/RequestInterface.kt
  app/src/main/java/how/about/it/repository/LoginRepository.kt
  app/src/main/java/how/about/it/repository/ProfileRepository.kt
  app/src/main/java/how/about/it/view/profile/ProfileFragment.kt
  app/src/main/java/how/about/it/viewmodel/ProfileViewModel.kt
Labels: feature

#188 #187 [feature] Vote Empty Emoji Click Event
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/java/how/about/it/view/comment/viewmodel/CommentViewModel.kt
  app/src/main/java/how/about/it/view/vote/adapter/VoteCommentAdapter.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#190 #189 [feature] init Emoji in VoteCommentAdapter
  app/src/main/java/how/about/it/view/vote/adapter/VoteCommentAdapter.kt
Labels: feature

#192 #191 [refactoring] VoteFragment
  app/src/main/java/how/about/it/util/FloatingAnimationUtil.kt
  app/src/main/java/how/about/it/util/HideKeyBoardUtil.kt
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/java/how/about/it/view/vote/viewmodel/VoteViewModel.kt
  app/src/main/res/layout/fragment_vote.xml
Labels: refactoring

#194 #193 [feature] Vote Comment Emoji
  app/src/main/java/how/about/it/network/vote/VoteInterface.kt
  app/src/main/java/how/about/it/network/vote/VoteService.kt
  app/src/main/java/how/about/it/network/vote/VoteServiceImpl.kt
  app/src/main/java/how/about/it/view/vote/adapter/VoteCommentAdapter.kt
  app/src/main/java/how/about/it/view/vote/repository/VoteRepository.kt
  app/src/main/java/how/about/it/view/vote/viewmodel/VoteViewModel.kt
Labels: feature

#196 #195 [refactoring] DeleteDialogUtil
  app/src/main/java/how/about/it/util/DeleteDialogUtil.kt
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/java/how/about/it/view/comment/adapter/ReCommentAdapter.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/java/how/about/it/view/vote/adapter/VoteCommentAdapter.kt
  app/src/main/res/values/strings.xml
Labels: refactoring

#200 #198 [refactoring] Hilt
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/how/about/it/MooMoolApplication.kt
  app/src/main/java/how/about/it/database/TempPostDatabase.kt
  app/src/main/java/how/about/it/di/RepositoryModule.kt
  app/src/main/java/how/about/it/di/ServiceModule.kt
  app/src/main/java/how/about/it/network/comment/CommentServiceImpl.kt
  app/src/main/java/how/about/it/network/feed/FeedServiceImpl.kt
  app/src/main/java/how/about/it/network/vote/VoteServiceImpl.kt
  app/src/main/java/how/about/it/view/comment/CommentFragment.kt
  app/src/main/java/how/about/it/view/comment/repository/CommentRepository.kt
  app/src/main/java/how/about/it/view/comment/viewmodel/CommentViewModel.kt
  app/src/main/java/how/about/it/view/comment/viewmodel/CommentViewModelFactory.kt
  app/src/main/java/how/about/it/view/commentupdate/CommentUpdateFragment.kt
  app/src/main/java/how/about/it/view/feed/FeedFragment.kt
  app/src/main/java/how/about/it/view/feed/repository/FeedRepository.kt
  app/src/main/java/how/about/it/view/feed/viewmodel/FeedViewModel.kt
  app/src/main/java/how/about/it/view/feed/viewmodel/FeedViewModelFactory.kt
  app/src/main/java/how/about/it/view/main/MainActivity.kt
  app/src/main/java/how/about/it/view/mypage/MyPageFragment.kt
  app/src/main/java/how/about/it/view/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/how/about/it/view/vote/VoteFragment.kt
  app/src/main/java/how/about/it/view/vote/repository/VoteRepository.kt
  app/src/main/java/how/about/it/view/vote/viewmodel/VoteViewModel.kt
  app/src/main/java/how/about/it/view/vote/viewmodel/VoteViewModelFactory.kt
  build.gradle
Labels: refactoring

#226 #225 [bug] VoteFragment fab_Vote visibility
  app/src/main/res/layout/fragment_vote.xml
Labels: bug

#228 #227 [feature] limit the number of characters in WriteFragment
  app/src/main/java/how/about/it/view/write/WriteFragment.kt
  app/src/main/res/values/strings.xml
Labels: feature

#230 #229 [layout] RvFeedTop Padding
  app/src/main/res/layout/fragment_feed.xml
Labels: layout

#232 #231 [feature] AutoLogin in SignupFragment
  app/src/main/java/how/about/it/view/signup/EmailSignupSetNicknameFragment.kt
  app/src/main/java/how/about/it/viewmodel/SignupViewModel.kt
Labels: feature

#234 #233 [layout] Modify Profile Layout
  app/src/main/java/how/about/it/view/profile/ProfileFragment.kt
  app/src/main/res/layout/fragment_profile.xml
Labels: layout

#236 #235 [bug] Set HideKeyboard in LoginFragment
  app/src/main/java/how/about/it/view/login/EmailLoginFragment.kt
  app/src/main/java/how/about/it/view/login/EmailPasswordResetFragment.kt
  app/src/main/res/layout/fragment_email_login.xml
  app/src/main/res/layout/fragment_email_password_reset.xml
Labels: bug

#238 #237 [bug] check E-mail Format in ResetPasswordFragment
  app/src/main/java/how/about/it/view/login/EmailPasswordResetFragment.kt
  app/src/main/res/layout/fragment_email_password_reset.xml
Labels: bug

#240 #239 [feature] NoticeFragment
  app/src/main/java/how/about/it/model/RequestNotice.kt
  app/src/main/java/how/about/it/network/RequestInterface.kt
  app/src/main/java/how/about/it/repository/NoticeRepository.kt
  app/src/main/java/how/about/it/view/notice/NoticeListAdapter.kt
  app/src/main/java/how/about/it/view/notice/NoticeListFragment.kt
  app/src/main/java/how/about/it/view/notice/NoticePostFragment.kt
  app/src/main/java/how/about/it/viewmodel/NoticeViewModel.kt
  app/src/main/res/layout/fragment_notice_list.xml
  app/src/main/res/layout/fragment_notice_post.xml
  app/src/main/res/layout/item_notice.xml
Labels: feature

#242 #241 [layout] Modify Layout SettingFragment
  app/src/main/java/how/about/it/view/setting/SettingFragment.kt
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/strings.xml
Labels: layout

#244 #243 [bug] TempWriteFragment Delete Button Color, Toast
  app/src/main/java/how/about/it/view/write/TempListWriteFragment.kt
  app/src/main/java/how/about/it/view/write/TempSavedWriteFragment.kt
  app/src/main/java/how/about/it/view/write/WriteFragment.kt
Labels: bug

#246 #245 [bug] Modify Password Hint Message
  app/src/main/java/how/about/it/view/signup/EmailSignupSetPasswordFragment.kt
  app/src/main/res/layout/fragment_email_signup_set_id.xml
  app/src/main/res/layout/fragment_email_signup_set_password.xml
  app/src/main/res/values/strings.xml
Labels: bug, layout

#248 #247 [layout] EditText Cursor Color
  app/src/main/res/drawable/background_cursor_color_pink.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: layout

#250 #249 [layout] Modify Login Message
  app/src/main/java/how/about/it/view/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: layout

#252 #251 [feature] SplashActivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/how/about/it/repository/LoginRepository.kt
  app/src/main/java/how/about/it/view/SplashActivity.kt
  app/src/main/java/how/about/it/view/login/LoginActivity.kt
  app/src/main/res/drawable/background_splash.xml
  app/src/main/res/values/themes.xml
Labels: feature, layout

#254 #253 [feature] Send Inquiry Email
  app/src/main/AndroidManifest.xml
  app/src/main/java/how/about/it/view/setting/SettingFragment.kt
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/values/strings.xml
Labels: feature, layout

#256 #255 [layout] Change Password Complete Message
  app/src/main/java/how/about/it/view/profile/ChangePasswordFragment.kt
  app/src/main/java/how/about/it/view/profile/ProfileFragment.kt
  app/src/main/java/how/about/it/viewmodel/ProfileViewModel.kt
Labels: layout

#260 #259 [layout] SplashActivity Status Bar Color
  app/src/main/res/values/themes.xml
Labels: layout

#263 #262 [feature] FeedTop Alpha
  app/src/main/res/layout/item_feed_top.xml
Labels: feature

#264 #261 [bug] Duplicate Timer
  app/src/main/java/com/moo/mool/view/vote/VoteFragment.kt
Labels: bug

#268 #267 [feature] init requestTopFeedList()
  app/src/main/java/com/moo/mool/view/feed/FeedFragment.kt
  app/src/main/java/com/moo/mool/view/feed/viewmodel/FeedViewModel.kt
Labels: feature

#270 #269 [refactoring] Update Project Name
  settings.gradle
Labels: refactoring

#274 #273 [bug] Temp Write Bug
  app/src/main/java/com/moo/mool/view/write/WriteFragment.kt
Labels: bug

#276 #275 [bug] LoginActivity Login Button
  app/src/main/java/com/moo/mool/view/login/LoginActivity.kt
Labels: bug

#278 #277 [feature] Send Reset Password E-mail
  app/src/main/java/com/moo/mool/model/RequestResetPassword.kt
  app/src/main/java/com/moo/mool/network/RequestInterface.kt
  app/src/main/java/com/moo/mool/repository/LoginRepository.kt
  app/src/main/java/com/moo/mool/view/login/EmailPasswordResetFragment.kt
  app/src/main/java/com/moo/mool/viewmodel/LoginViewModel.kt
Labels: feature

#280 #279 [layout] Loading Animation
  app/src/main/java/com/moo/mool/util/LodingDialog.kt
  app/src/main/java/com/moo/mool/view/login/EmailPasswordResetFragment.kt
  app/src/main/res/drawable/animation_loading.xml
  app/src/main/res/drawable/ic_loading.xml
Labels: feature, layout
