Repository dnd-side-project/dnd-5th-3-android, pull requests merged in 2021-09, with the labels that each got.

#282 #281 [Bug] EmailLoginFragment, WriteFragmen
  app/src/main/java/com/moo/mool/view/login/EmailLoginFragment.kt
  app/src/main/java/com/moo/mool/view/write/WriteFragment.kt
  app/src/main/res/layout/fragment_email_login.xml
  app/src/main/res/values/strings.xml
Labels: bug

#284 #283 [bug] LoadingDialogUtil Typo, TempSavedWriteFragment Background
  app/src/main/java/com/moo/mool/util/LoadingDialogUtil.kt
  app/src/main/java/com/moo/mool/view/login/EmailPasswordResetFragment.kt
  app/src/main/java/com/moo/mool/view/write/TempSavedWriteFragment.kt
  app/src/main/res/values/strings.xml
Labels: bug

#286 #285 [bug] Keyboard freezes for few Seconds
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: bug

#288 #287 [feature] Set Emoji Motion Display Value
  app/src/main/java/com/moo/mool/database/SharedManager.kt
  app/src/main/java/com/moo/mool/repository/SettingRepository.kt
  app/src/main/java/com/moo/mool/view/setting/SettingMotionFragment.kt
  app/src/main/java/com/moo/mool/viewmodel/SettingViewModel.kt
Labels: feature

#291 #290 [feature] Change Transition Fragment After WriteFragment is Completed
  app/src/main/java/com/moo/mool/repository/WriteRepository.kt
  app/src/main/java/com/moo/mool/view/write/WriteFragment.kt
  app/src/main/java/com/moo/mool/viewmodel/WriteViewModel.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: feature

#293 #292 [refactoring] HideKeyBoardUtil
  app/src/main/java/com/moo/mool/util/HideKeyBoardUtil.kt
  app/src/main/java/com/moo/mool/view/login/EmailLoginFragment.kt
  app/src/main/java/com/moo/mool/view/login/EmailPasswordResetFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetIDFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetNicknameFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetPasswordFragment.kt
Labels: refactoring

#295 #294 [refactoring] LoginActivity Navigation
  app/src/main/java/com/moo/mool/view/login/EmailLoginFragment.kt
  app/src/main/java/com/moo/mool/view/login/EmailPasswordResetFragment.kt
  app/src/main/java/com/moo/mool/view/login/LoginActivity.kt
  app/src/main/java/com/moo/mool/view/login/LoginMainFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetIDFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetNicknameFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetPasswordFragment.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_login_main.xml
  app/src/main/res/navigation/nav_graph_login.xml
Labels: refactoring

#297 #296 [layout] LoadingAnimation in SplashActivity
  app/src/main/java/com/moo/mool/view/SplashActivity.kt
Labels: layout

#299 #298 [bug] Duplicate Posting
  app/src/main/java/com/moo/mool/view/write/WriteFragment.kt
Labels: bug

#301 #300 [layout] Comment Post Text
  app/src/main/java/com/moo/mool/view/comment/CommentFragment.kt
  app/src/main/java/com/moo/mool/view/vote/VoteFragment.kt
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/values/strings.xml
Labels: layout

#303 #302 [feature] maxLength 500
  app/src/main/java/com/moo/mool/view/comment/CommentFragment.kt
  app/src/main/java/com/moo/mool/view/commentupdate/CommentUpdateFragment.kt
  app/src/main/java/com/moo/mool/view/vote/VoteFragment.kt
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/values/strings.xml
Labels: feature

#305 #304 [feature] HideKeyBoardUtil in CommentFragment
  app/src/main/java/com/moo/mool/view/comment/CommentFragment.kt
Labels: feature

#307 #306 [refactoring] package
  app/src/main/java/com/moo/mool/network/comment/CommentInterface.kt
  app/src/main/java/com/moo/mool/network/comment/CommentService.kt
  app/src/main/java/com/moo/mool/network/comment/CommentServiceImpl.kt
  app/src/main/java/com/moo/mool/network/vote/VoteInterface.kt
  app/src/main/java/com/moo/mool/network/vote/VoteService.kt
  app/src/main/java/com/moo/mool/network/vote/VoteServiceImpl.kt
  app/src/main/java/com/moo/mool/util/BindingAdapter.kt
  app/src/main/java/com/moo/mool/view/comment/CommentFragment.kt
  app/src/main/java/com/moo/mool/view/comment/adapter/ReCommentAdapter.kt
  app/src/main/java/com/moo/mool/view/comment/model/RequestPostEmoji.kt
  app/src/main/java/com/moo/mool/view/comment/model/RequestPostReComment.kt
  app/src/main/java/com/moo/mool/view/comment/model/RequestPutEmoji.kt
  app/src/main/java/com/moo/mool/view/comment/model/ResponseComment.kt
  app/src/main/java/com/moo/mool/view/comment/model/ResponsePostEmoji.kt
  app/src/main/java/com/moo/mool/view/comment/repository/CommentRepository.kt
  app/src/main/java/com/moo/mool/view/comment/viewmodel/CommentViewModel.kt
  app/src/main/java/com/moo/mool/view/commentupdate/model/RequestPutComment.kt
  app/src/main/java/com/moo/mool/view/feed/model/ResponseMainFeed.kt
  app/src/main/java/com/moo/mool/view/vote/VoteFragment.kt
  app/src/main/java/com/moo/mool/view/vote/adapter/VoteCommentAdapter.kt
  app/src/main/java/com/moo/mool/view/vote/model/RequestCommentId.kt
  app/src/main/java/com/moo/mool/view/vote/model/RequestPostComment.kt
  app/src/main/java/com/moo/mool/view/vote/model/RequestVote.kt
  app/src/main/java/com/moo/mool/view/vote/model/ResponseFeedDetail.kt
  app/src/main/java/com/moo/mool/view/vote/model/ResponsePostComment.kt
  app/src/main/java/com/moo/mool/view/vote/repository/VoteRepository.kt
  app/src/main/java/com/moo/mool/view/vote/viewmodel/VoteViewModel.kt
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_re_comment.xml
Labels: refactoring

#311 #310 [refactoring] Hilt Apply in Login, Signup
  app/src/main/java/com/moo/mool/database/SharedManager.kt
  app/src/main/java/com/moo/mool/di/RepositoryModule.kt
  app/src/main/java/com/moo/mool/di/ServiceModule.kt
  app/src/main/java/com/moo/mool/network/RequestInterface.kt
  app/src/main/java/com/moo/mool/network/RequestToServer.kt
  app/src/main/java/com/moo/mool/network/login/LoginInterface.kt
  app/src/main/java/com/moo/mool/network/login/LoginService.kt
  app/src/main/java/com/moo/mool/network/login/LoginServiceImpl.kt
  app/src/main/java/com/moo/mool/repository/LoginRepository.kt
  app/src/main/java/com/moo/mool/repository/SignupRepository.kt
  app/src/main/java/com/moo/mool/view/SplashActivity.kt
  app/src/main/java/com/moo/mool/view/login/EmailLoginFragment.kt
  app/src/main/java/com/moo/mool/view/login/EmailPasswordResetFragment.kt
  app/src/main/java/com/moo/mool/view/login/LoginActivity.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetIDFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetNicknameFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetPasswordFragment.kt
  app/src/main/java/com/moo/mool/viewmodel/LoginViewModel.kt
  app/src/main/java/com/moo/mool/viewmodel/SignupViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_email_login.xml
  app/src/main/res/layout/fragment_email_password_reset.xml
  app/src/main/res/layout/fragment_login_main.xml
Labels: refactoring

#313 #312 [bug] Set SingleLine in ProfieFragment, WriteFragment
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_write.xml
Labels: bug

#316 #315 [bug] Temp Write Bug
  app/src/main/java/com/moo/mool/database/Post.kt
  app/src/main/java/com/moo/mool/view/write/WriteFragment.kt
Labels: bug

#318 #317 [bug] Modify Delete Account Message
  app/src/main/res/values/strings.xml
Labels: bug

#320 #314 [bug] Modify Password Criteria
  app/src/main/java/com/moo/mool/view/profile/ChangePasswordFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetPasswordFragment.kt
  app/src/main/res/layout/fragment_email_signup_set_password.xml
  app/src/main/res/values/strings.xml
Labels: bug

#322 #321 [layout] SignupFragment
  app/src/main/res/layout/fragment_email_signup_set_nickname.xml
  app/src/main/res/values/strings.xml
Labels: layout

#324 #323 [bug] Login Main Fragment
  app/src/main/res/drawable/activity_login_background.xml
Labels: bug, layout

#326 #325 [bug] TempWriteFragment
  app/src/main/java/com/moo/mool/database/TempPostDao.kt
  app/src/main/java/com/moo/mool/di/RepositoryModule.kt
  app/src/main/java/com/moo/mool/repository/SettingRepository.kt
  app/src/main/java/com/moo/mool/repository/TempPostRepository.kt
  app/src/main/java/com/moo/mool/view/setting/SettingFragment.kt
  app/src/main/java/com/moo/mool/view/setting/SettingMotionFragment.kt
  app/src/main/java/com/moo/mool/viewmodel/SettingViewModel.kt
Labels: bug

#328 #327 [bug] WriteFragment Server Error
  app/src/main/java/com/moo/mool/view/write/WriteFragment.kt
Labels: bug

#330 #329 [bug] limit the number of characters about Emoji
  app/src/main/java/com/moo/mool/util/EdittextCount.kt
  app/src/main/java/com/moo/mool/view/comment/CommentFragment.kt
  app/src/main/java/com/moo/mool/view/profile/ProfileFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetNicknameFragment.kt
  app/src/main/java/com/moo/mool/view/write/WriteFragment.kt
Labels: bug

#332 #331 [bug] Dialog Error about ChangeNickname, ResetPassword
  app/src/main/java/com/moo/mool/view/login/EmailPasswordResetFragment.kt
  app/src/main/java/com/moo/mool/view/profile/ProfileFragment.kt
  app/src/main/java/com/moo/mool/viewmodel/LoginViewModel.kt
Labels: bug

#334 #333 [feature] Set Link Policy Information
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetNicknameFragment.kt
Labels: feature

#336 #335 [bug] Set Hide Undeveloped Functions
  app/src/main/java/com/moo/mool/view/login/LoginMainFragment.kt
  app/src/main/java/com/moo/mool/view/setting/SettingFragment.kt
Labels: bug

#338 #337 [layout] Material Button LetterSpacing
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_on_boarding.xml
Labels: layout

#340 #339 [layout] LetterSpacing
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/fragment_write.xml
Labels: layout

#342 #341 [bug] Modify URL
  app/src/main/java/com/moo/mool/view/setting/SettingFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetNicknameFragment.kt
Labels: bug

#344 #343 [refactoring] Home and MyPage
  app/src/main/java/com/moo/mool/network/feed/FeedInterface.kt
  app/src/main/java/com/moo/mool/network/feed/FeedService.kt
  app/src/main/java/com/moo/mool/network/mypage/MyPageInterface.kt
  app/src/main/java/com/moo/mool/network/mypage/MyPageService.kt
  app/src/main/java/com/moo/mool/util/AutoClearedValue.kt
  app/src/main/java/com/moo/mool/util/BindingAdapter.kt
  app/src/main/java/com/moo/mool/util/NavigationUtil.kt
  app/src/main/java/com/moo/mool/util/RepeatOnLifecycleUtil.kt
  app/src/main/java/com/moo/mool/view/feed/FeedFragment.kt
  app/src/main/java/com/moo/mool/view/feed/adapter/FeedBottomAdapter.kt
  app/src/main/java/com/moo/mool/view/feed/adapter/FeedTopAdapter.kt
  app/src/main/java/com/moo/mool/view/feed/model/ResponseMainFeed.kt
  app/src/main/java/com/moo/mool/view/feed/repository/FeedRepository.kt
  app/src/main/java/com/moo/mool/view/feed/viewmodel/FeedViewModel.kt
  app/src/main/java/com/moo/mool/view/mypage/MyPageFragment.kt
  app/src/main/java/com/moo/mool/view/mypage/adapter/MyPageFeedAdapter.kt
  app/src/main/java/com/moo/mool/view/mypage/repository/MyPageRepository.kt
  app/src/main/java/com/moo/mool/view/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_feed_bottom.xml
  app/src/main/res/layout/item_feed_top.xml
Labels: refactoring

#347 #346 [refactoring] Emoji
  app/src/main/java/com/moo/mool/di/RepositoryModule.kt
  app/src/main/java/com/moo/mool/di/ServiceModule.kt
  app/src/main/java/com/moo/mool/network/RequestToServer.kt
  app/src/main/java/com/moo/mool/network/comment/CommentInterface.kt
  app/src/main/java/com/moo/mool/network/comment/CommentService.kt
  app/src/main/java/com/moo/mool/network/comment/CommentServiceImpl.kt
  app/src/main/java/com/moo/mool/network/emoji/EmojiInterface.kt
  app/src/main/java/com/moo/mool/network/emoji/EmojiService.kt
  app/src/main/java/com/moo/mool/network/emoji/EmojiServiceImpl.kt
  app/src/main/java/com/moo/mool/util/BindingAdapter.kt
  app/src/main/java/com/moo/mool/util/GetIsMineUtil.kt
  app/src/main/java/com/moo/mool/view/comment/CommentFragment.kt
  app/src/main/java/com/moo/mool/view/comment/adapter/ReplyAdapter.kt
  app/src/main/java/com/moo/mool/view/comment/repository/CommentRepository.kt
  app/src/main/java/com/moo/mool/view/comment/repository/EmojiRepository.kt
  app/src/main/java/com/moo/mool/view/comment/viewmodel/CommentViewModel.kt
  app/src/main/java/com/moo/mool/view/feed/adapter/FeedBottomAdapter.kt
  app/src/main/java/com/moo/mool/view/feed/adapter/FeedTopAdapter.kt
  app/src/main/java/com/moo/mool/view/mypage/adapter/MyPageFeedAdapter.kt
  app/src/main/java/com/moo/mool/view/vote/VoteFragment.kt
  app/src/main/java/com/moo/mool/view/vote/adapter/VoteCommentAdapter.kt
  app/src/main/res/drawable/background_small_emoji_checked_round_20.xml
  app/src/main/res/layout/fragment_comment.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_re_comment.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: refactoring

#349 #348 [bug] Token Refresh Bug
  app/src/main/java/com/moo/mool/repository/LoginRepository.kt
Labels: bug

#350 #1 [feature] Social Account Signup, Login
  app/src/main/java/com/moo/mool/network/RequestInterface.kt
  app/src/main/java/com/moo/mool/repository/LoginRepository.kt
  app/src/main/java/com/moo/mool/repository/ProfileRepository.kt
  app/src/main/java/com/moo/mool/view/login/LoginMainFragment.kt
  app/src/main/java/com/moo/mool/view/profile/ProfileFragment.kt
  app/src/main/java/com/moo/mool/viewmodel/LoginViewModel.kt
  app/src/main/java/com/moo/mool/viewmodel/ProfileViewModel.kt
  app/src/main/res/layout/fragment_login_main.xml
  app/src/main/res/navigation/nav_graph_login.xml
Labels: feature, layout

#352 #351 [layout] Profile Fragment
  app/src/main/res/layout/fragment_profile.xml
Labels: layout

#354 #353 [refactoring] Vote
  app/src/main/java/com/moo/mool/network/vote/VoteInterface.kt
  app/src/main/java/com/moo/mool/network/vote/VoteService.kt
  app/src/main/java/com/moo/mool/network/vote/VoteServiceImpl.kt
  app/src/main/java/com/moo/mool/view/comment/CommentFragment.kt
  app/src/main/java/com/moo/mool/view/comment/viewmodel/CommentViewModel.kt
  app/src/main/java/com/moo/mool/view/vote/VoteFragment.kt
  app/src/main/java/com/moo/mool/view/vote/repository/VoteRepository.kt
  app/src/main/java/com/moo/mool/view/vote/viewmodel/VoteViewModel.kt
  app/src/main/res/layout/fragment_vote.xml
Labels: refactoring

#356 #355 [layout] Icon
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_moomool.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_moomool.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_moomool.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_moomool.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_moomool.png
Labels: layout

#358 #357 [Bug] Back Button, Social Email Check
  app/src/main/java/com/moo/mool/view/profile/ChangePasswordFragment.kt
  app/src/main/java/com/moo/mool/view/profile/ProfileFragment.kt
  app/src/main/java/com/moo/mool/viewmodel/ProfileViewModel.kt
  app/src/main/res/navigation/nav_graph_login.xml
Labels: bug, refactoring

#360 #359 [bug] VoteFragment Repeat Lottie
  app/src/main/java/com/moo/mool/view/vote/VoteFragment.kt
  app/src/main/java/com/moo/mool/view/vote/viewmodel/VoteViewModel.kt
Labels: bug

#362 #361 [refactoring] ProfileFragment
  app/src/main/java/com/moo/mool/repository/ProfileRepository.kt
  app/src/main/java/com/moo/mool/util/ActiveButtonUtil.kt
  app/src/main/java/com/moo/mool/util/DefaultDialogUtil.kt
  app/src/main/java/com/moo/mool/util/ToolbarDecorationUtil.kt
  app/src/main/java/com/moo/mool/view/profile/ProfileFragment.kt
  app/src/main/java/com/moo/mool/viewmodel/ProfileViewModel.kt
  app/src/main/res/values/strings.xml
Labels: refactoring

#364 #363 [bug] LoginFragment
  app/src/main/java/com/moo/mool/repository/LoginRepository.kt
  app/src/main/java/com/moo/mool/view/login/LoginMainFragment.kt
Labels: bug

#366 #365 [refactoring] Dialog
  app/src/main/java/com/moo/mool/util/DefaultDialogUtil.kt
  app/src/main/java/com/moo/mool/view/profile/ProfileFragment.kt
Labels: refactoring

#368 #367 [bug] ChangePasswordFragment
  app/src/main/java/com/moo/mool/util/ActiveButtonUtil.kt
  app/src/main/java/com/moo/mool/view/profile/ChangePasswordFragment.kt
  app/src/main/java/com/moo/mool/view/profile/ProfileFragment.kt
Labels: bug, refactoring

#370 #369 [refactoring] LoginFragment
  app/src/main/java/com/moo/mool/util/ToolbarDecorationUtil.kt
  app/src/main/java/com/moo/mool/view/login/EmailLoginFragment.kt
  app/src/main/java/com/moo/mool/view/login/EmailPasswordResetFragment.kt
  app/src/main/java/com/moo/mool/view/login/LoginMainFragment.kt
Labels: refactoring

#372 #371 [refactoring] signupFragment
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetIDFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetNicknameFragment.kt
  app/src/main/java/com/moo/mool/view/signup/EmailSignupSetPasswordFragment.kt
  app/src/main/res/values/strings.xml
Labels: refactoring

#374 #373 [refactoring] WriteFragment, TempWriteFragment
  app/src/main/java/com/moo/mool/view/write/TempListWriteFragment.kt
  app/src/main/java/com/moo/mool/view/write/TempSavedWriteFragment.kt
  app/src/main/java/com/moo/mool/view/write/WriteFragment.kt
Labels: refactoring

#376 #375 [refactoring] SettingFragment
  app/src/main/java/com/moo/mool/view/setting/SettingFragment.kt
Labels: refactoring
